CREATE TABLE LANGUAGE (
	ID_LANGUAGE INT PRIMARY KEY IDENTITY(1, 1),
	DESCRIPTION VARCHAR(50) NOT NULL,
	CODE VARCHAR(15) NOT NULL,
	COUNTRY_CODE VARCHAR(5) NOT NULL
)

CREATE TABLE RESOLUTION (
	ID_RESOLUTION INT PRIMARY KEY IDENTITY(1, 1),
	DESCRIPTION VARCHAR(30) NOT NULL,
	PIXELS VARCHAR(20) NOT NULL
)

CREATE TABLE CATEGORY (
	ID_CATEGORY INT PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(30) NOT NULL
)

CREATE TABLE CONTENT (
	ID_CONTENT INT PRIMARY KEY IDENTITY(1, 1),
	DESCRIPTION VARCHAR(50) NOT NULL
)

CREATE TABLE FILM (
	ID_FILM INT PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(50) NOT NULL,
	DURATION SMALLINT NOT NULL,
	THUMBNAIL VARCHAR(200) NOT NULL,
	YEAR SMALLINT NOT NULL,
	CREDITS_START SMALLINT NULL,
	KIDS_CONTENT BIT NOT NULL,
	ID_LANGUAGE INT NOT NULL,
	FOREIGN KEY (ID_LANGUAGE)
	REFERENCES LANGUAGE(ID_LANGUAGE)
)

CREATE TABLE SERIES (
	ID_SERIES INT PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(50) NOT NULL,
	THUMBNAIL VARCHAR(200) NOT NULL,
	KIDS_CONTENT BIT NOT NULL,
	ID_LANGUAGE INT NOT NULL,
	FOREIGN KEY (ID_LANGUAGE)
	REFERENCES LANGUAGE(ID_LANGUAGE)
)

CREATE TABLE SERIES_EPISODE (
	ID_SERIES_EPISODE INT PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(50) NOT NULL,
	SEASON SMALLINT NOT NULL,
	EPISODE SMALLINT NOT NULL,
	DURATION SMALLINT NOT NULL,
	THUMBNAIL VARCHAR(200) NOT NULL,
	YEAR SMALLINT NOT NULL,
	OPENING_START SMALLINT NULL,
	CREDITS_START SMALLINT NULL,
	ID_SERIES INT NOT NULL,
	ID_CONTENT INT NOT NULL,
	FOREIGN KEY (ID_SERIES)
	REFERENCES SERIES(ID_SERIES)
)

CREATE TABLE CATALOG_REGION (
	ID_CATALOG_REGION INT PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(50) NOT NULL,
	CLASSIFICATION VARCHAR(5) NULL,
	SYNOPSIS VARCHAR(200) NOT NULL,
	ID_FILM INT NULL,
	ID_SERIES INT NULL,
	ID_LANGUAGE INT NOT NULL,
	FOREIGN KEY (ID_FILM)
	REFERENCES FILM(ID_FILM),
	FOREIGN KEY (ID_SERIES)
	REFERENCES SERIES(ID_SERIES),
	FOREIGN KEY (ID_LANGUAGE)
	REFERENCES LANGUAGE(ID_LANGUAGE)
)

CREATE TABLE CATALOG_REGION_ITEM (
	ID_CATALOG_REGION_ITEM INT PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(50) NOT NULL,
	CLASSIFICATION VARCHAR(5) NOT NULL,
	SYNOPSIS VARCHAR(200) NOT NULL,
	ID_CATALOG_REGION INT NOT NULL,
	ID_SERIES_EPISODE INT NOT NULL,
	FOREIGN KEY (ID_CATALOG_REGION)
	REFERENCES CATALOG_REGION(ID_CATALOG_REGION),
	FOREIGN KEY (ID_SERIES_EPISODE)
	REFERENCES SERIES_EPISODE(ID_SERIES_EPISODE)
)

CREATE TABLE CATALOG_CATEGORY (
	ID_CATALOG_CATEGORY INT PRIMARY KEY IDENTITY(1, 1),
	ID_CATEGORY INT NOT NULL,
	ID_FILM INT NULL,
	ID_SERIES INT NULL,
	FOREIGN KEY (ID_CATEGORY)
	REFERENCES CATEGORY(ID_CATEGORY),
	FOREIGN KEY (ID_FILM)
	REFERENCES FILM(ID_FILM),
	FOREIGN KEY (ID_SERIES)
	REFERENCES SERIES(ID_SERIES),
)

CREATE TABLE CATALOG_CONTENT (
	ID_CATALOG_CONTENT INT PRIMARY KEY IDENTITY(1, 1),
	ID_CONTENT INT NOT NULL,
	ID_FILM INT NULL,
	ID_SERIES_EPISODE INT NULL,
	FOREIGN KEY (ID_CONTENT)
	REFERENCES CONTENT(ID_CONTENT),
	FOREIGN KEY (ID_FILM)
	REFERENCES FILM(ID_FILM),
	FOREIGN KEY (ID_SERIES_EPISODE)
	REFERENCES SERIES_EPISODE(ID_SERIES_EPISODE),
)

CREATE TABLE CAST (
	ID_CAST INT PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(100) NOT NULL,
	CHARACTER VARCHAR(100) NOT NULL,
	ID_FILM INT NULL,
	ID_SERIES INT NULL,
	SEASON SMALLINT NULL,
	FOREIGN KEY (ID_FILM)
	REFERENCES FILM(ID_FILM),
	FOREIGN KEY (ID_SERIES)
	REFERENCES SERIES(ID_SERIES)
)

CREATE TABLE MEDIA (
	ID_MEDIA INT PRIMARY KEY IDENTITY(1, 1),
	PATH VARCHAR(200) NOT NULL,
	ID_RESOLUTION INT NOT NULL,
	ID_FILM INT NULL,
	ID_SERIES_EPISODE INT NULL,
	FOREIGN KEY (ID_RESOLUTION)
	REFERENCES RESOLUTION(ID_RESOLUTION),
	FOREIGN KEY (ID_FILM)
	REFERENCES FILM(ID_FILM),
	FOREIGN KEY (ID_SERIES_EPISODE)
	REFERENCES SERIES_EPISODE(ID_SERIES_EPISODE)
)

CREATE TABLE AUDIO (
	ID_AUDIO INT PRIMARY KEY IDENTITY(1, 1),
	PATH VARCHAR(200) NOT NULL,
	ID_LANGUAGE INT NOT NULL,
	ID_FILM INT NULL,
	ID_SERIES_EPISODE INT NULL,
	FOREIGN KEY (ID_LANGUAGE)
	REFERENCES LANGUAGE(ID_LANGUAGE),
	FOREIGN KEY (ID_FILM)
	REFERENCES FILM(ID_FILM),
	FOREIGN KEY (ID_SERIES_EPISODE)
	REFERENCES SERIES_EPISODE(ID_SERIES_EPISODE)
)

CREATE TABLE SUBTITLES (
	ID_SUBTITLES INT PRIMARY KEY IDENTITY(1, 1),
	PATH VARCHAR(200) NOT NULL,
	ID_LANGUAGE INT NOT NULL,
	ID_FILM INT NULL,
	ID_SERIES_EPISODE INT NULL,
	FOREIGN KEY (ID_LANGUAGE)
	REFERENCES LANGUAGE(ID_LANGUAGE),
	FOREIGN KEY (ID_FILM)
	REFERENCES FILM(ID_FILM),
	FOREIGN KEY (ID_SERIES_EPISODE)
	REFERENCES SERIES_EPISODE(ID_SERIES_EPISODE)
)

CREATE TABLE [USER] (
	ID_USER INT PRIMARY KEY IDENTITY(1, 1),
	EMAIL VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL
)

CREATE TABLE PROFILE (
	ID_PROFILE INT PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(30) NOT NULL,
	AVATAR VARCHAR(200) NULL,
	ID_USER INT NOT NULL
	FOREIGN KEY (ID_USER)
	REFERENCES [USER](ID_USER)
)

CREATE TABLE MY_LIST (
	ID_MY_LIST INT PRIMARY KEY IDENTITY(1, 1),
	ID_FILM INT NULL,
	ID_SERIES INT NULL,
	ID_PROFILE INT NOT NULL
	FOREIGN KEY (ID_PROFILE)
	REFERENCES PROFILE(ID_PROFILE)
)

CREATE TABLE KEEP_WHATCHING (
	ID_KEEP_WHATCHING INT PRIMARY KEY IDENTITY(1, 1),
	ID_FILM INT NULL,
	ID_SERIES_EPISODE INT NULL,
	TIME SMALLINT NOT NULL,
	ID_PROFILE INT NOT NULL
	FOREIGN KEY (ID_PROFILE)
	REFERENCES PROFILE(ID_PROFILE)
)